export const EXAMS = [
  {
    id: 'ssc-gd',
    name: 'SSC GD Constable',
    category: 'Federal',
    color: 'bg-blue-500',
    icon: '🔒',
    subjects: ['Reasoning', 'General Awareness', 'Mathematics', 'English'],
  },
  {
    id: 'ssc-cgl',
    name: 'SSC CGL',
    category: 'Federal',
    color: 'bg-purple-500',
    icon: '📊',
    subjects: ['Quantitative Aptitude', 'General Intelligence', 'English', 'General Awareness'],
  },
  {
    id: 'ssc-mts',
    name: 'SSC MTS',
    category: 'Federal',
    color: 'bg-green-500',
    icon: '✍️',
    subjects: ['Numerical Aptitude', 'Reasoning', 'English', 'General Awareness'],
  },
  {
    id: 'ssc-cpo',
    name: 'SSC CPO',
    category: 'Federal',
    color: 'bg-red-500',
    icon: '🚔',
    subjects: ['Quantitative Aptitude', 'General Intelligence', 'English', 'General Awareness'],
  },
  {
    id: 'ras',
    name: 'RAS (RPSC)',
    category: 'State',
    color: 'bg-orange-500',
    icon: '🏛️',
    subjects: ['General Knowledge', 'Hindi', 'English', 'Reasoning', 'CSAT'],
  },
  {
    id: 'army',
    name: 'Indian Army',
    category: 'Defence',
    color: 'bg-yellow-600',
    icon: '⚔️',
    subjects: ['Mathematics', 'General Science', 'English', 'General Knowledge'],
  },
  {
    id: 'bstc',
    name: 'BSTC (D.El.Ed)',
    category: 'State',
    color: 'bg-pink-500',
    icon: '🎓',
    subjects: ['Child Development', 'English', 'Hindi', 'Science & Maths', 'Social Studies'],
  },
  {
    id: 'patwari',
    name: 'Patwari',
    category: 'State',
    color: 'bg-indigo-500',
    icon: '📋',
    subjects: ['Reasoning', 'General Knowledge', 'Hindi', 'English', 'Numerical Ability'],
  },
  {
    id: 'teacher',
    name: 'Teacher',
    category: 'State',
    color: 'bg-cyan-500',
    icon: '👨‍🏫',
    subjects: ['Pedagogy', 'Subject Knowledge', 'Child Development', 'Inclusive Education'],
  },
  {
    id: 'reet',
    name: 'REET',
    category: 'State',
    color: 'bg-teal-500',
    icon: '📚',
    subjects: ['Child Development', 'Mathematics', 'Science', 'Social Studies', 'English', 'Hindi'],
    levels: ['Level 1 (Class 1-5)', 'Level 2 (Class 6-8)', 'Level 3 (Class 9-10)', 'Level 4 (Class 11-12)'],
  },
  {
    id: '4th-grade',
    name: '4th Grade',
    category: 'State',
    color: 'bg-lime-500',
    icon: '🏅',
    subjects: ['Hindi', 'English', 'Reasoning', 'General Knowledge'],
  },
];

export const SUBJECTS = [
  { id: 'reasoning', name: 'Reasoning', icon: '🧩' },
  { id: 'mathematics', name: 'Mathematics', icon: '🔢' },
  { id: 'english', name: 'English', icon: '📝' },
  { id: 'hindi', name: 'Hindi', icon: '🗣️' },
  { id: 'gk', name: 'General Knowledge', icon: '🌍' },
  { id: 'science', name: 'Science', icon: '🔬' },
  { id: 'history', name: 'History', icon: '📖' },
  { id: 'geography', name: 'Geography', icon: '🗺️' },
];

export const DIFFICULTY_LEVELS = [
  { id: 'beginner', name: 'Beginner', badge: '⭐' },
  { id: 'intermediate', name: 'Intermediate', badge: '⭐⭐' },
  { id: 'advanced', name: 'Advanced', badge: '⭐⭐⭐' },
];
